WebsiteBanHang/Models/MOMO/MomoCreatePaymentResponseModel.cs
namespace WebsiteBanHang.Models.MOMO;

public class MomoCreatePaymentResponseModel
{
    public string RequestId { get; set; }
    public int ErrorCode { get; set; }
    public string OrderId { get; set; }
    public string Message { get; set; }
    public string LocalMessage { get; set; }
    public string RequestType { get; set; }
    public string PayUrl { get; set; }
    public string Signature { get; set; }
    public string QrCodeUrl { get; set; }
    public string Deeplink { get; set; }
    public string DeeplinkWebInApp { get; set; }
}

WebsiteBanHang/Models/MOMO/MomoExecuteResponseModel.cs
namespace WebsiteBanHang.Models.MOMO;

public class MomoExecuteResponseModel
{
    public string OrderId { get; set; }
    public string Amount { get; set; }
    public string OrderInfo { get; set; }
}

WebsiteBanHang/Models/MOMO/MomoOptionModel.cs
namespace WebsiteBanHang.Models.MOMO;

public class MomoOptionModel
{
    public string MomoApiUrl { get; set; }
    public string SecretKey { get; set; }
    public string AccessKey { get; set; }
    public string ReturnUrl { get; set; }
    public string NotifyUrl { get; set; }
    public string PartnerCode { get; set; }
    public string RequestType { get; set; }
}

WebsiteBanHang/Controllers/MomoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebsiteBanHang.Models;
using WebsiteBanHang.Repositories;
using WebsiteBanHang.Services;

namespace WebsiteBanHang.Controllers
{
    [Authorize]
    public class MomoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMomoService _momoService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IProductRepository _productRepository;

        public MomoController(IMomoService momoService, ApplicationDbContext context, UserManager<ApplicationUser> userManager, IProductRepository productRepository)
        {
            _momoService = momoService;
            _context = context;
            _userManager = userManager;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index(decimal amount)
        {
            // Lấy ID của người dùng hiện tại
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return Unauthorized(); // Hoặc phản hồi phù hợp khác
            }

            // Lấy thông tin người dùng từ UserManager
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound(); // Hoặc phản hồi phù hợp khác
            }

            // Lấy tên đầy đủ của người dùng
            var fullName = user.FullName; // Giả sử FullName là một thuộc tính của ApplicationUser

            // Truyền dữ liệu sang View
            ViewBag.FullName = fullName;
            ViewBag.TotalAmount = amount;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePaymentUrl(OrderInfoModel model)
        {
            var response = await _momoService.CreatePaymentAsync(model);

            return Redirect(response.PayUrl);
        }

        [HttpGet]
        public IActionResult PaymentCallBack()
        {
            var response = _momoService.PaymentExecuteAsync(HttpContext.Request.Query);
            return View(response);
        }

    }
}

WebsiteBanHang/Views/Momo/Index.cshtml
@{
    ViewData["Title"] = "Thanh toán Momo";
    var postUrl = "thanh-toan-momo";
    var formattedTotalAmount = String.Format("{0:N0}", ViewBag.TotalAmount);
}

<div class="bg-light py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="text-center mb-4">
                    <h1 class="display-4">Thanh toán Momo</h1>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form asp-controller="Momo" asp-action="CreatePaymentUrl" id="frmCreateOrder" method="post">
                            <div class="form-group">
                                <label for="FullName">Tên khách hàng</label>
                                <input class="form-control" id="FullName" name="FullName" type="text" value="@ViewBag.FullName" required>
                            </div>
                            <div class="form-group">
                                <label for="Amount">Số tiền</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">VNĐ</span>
                                    </div>
                                    <input class="form-control" id="Amount" name="Amount" type="text" value="@formattedTotalAmount" readonly required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="OrderInfo">Nội dung thanh toán</label>
                                <textarea class="form-control" cols="20" id="OrderInfo" name="OrderInfo" rows="3" required>Thanh toán tại CCG TechZone</textarea>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Thanh toán (Checkout)</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebsiteBanHang/Views/Momo/PaymentCallBack.cshtml
@model WebsiteBanHang.Models.MOMO.MomoExecuteResponseModel

@{
    ViewData["Title"] = "Thanh Toán Thành Công";
    var postUrl = "tich-hop-thanh-toan-momo-voi-asp-net-core-7d5e4hP";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg">
                <div class="card-header text-center bg-success text-white">
                    <h3 class="mb-0">Thanh Toán Thành Công</h3>
                </div>
                <div class="card-body">
                    <div class="text-center mb-4">
                        <i class="fas fa-check-circle fa-5x text-success"></i>
                    </div>
                    <h5 class="card-title">Chúc mừng bạn đã thanh toán thành công!</h5>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Order ID:</strong></p>
                        </div>
                        <div class="col-md-6">
                            <p>@Model.OrderId</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Số tiền:</strong></p>
                        </div>
                        <div class="col-md-6">
                            <p>@Model.Amount</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Order Info:</strong></p>
                        </div>
                        <div class="col-md-6">
                            <p>@Model.OrderInfo</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <form method="post" asp-controller="Home" asp-action="Index">
                        <button type="submit" class="btn btn-info">Tiếp tục mua hàng</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>